# Generated by Django 5.1.3 on 2024-11-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_appointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appointment',
            new_name='Appointment1',
        ),
    ]
